#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT_DIR="${ROOT_DIR}/evidence/drills/${STAMP}"

mkdir -p "${OUT_DIR}"

cp "${ROOT_DIR}/drills/templates/SEV_ESCALATION_DRILL_REPORT_TEMPLATE.md" \
  "${OUT_DIR}/SEV_ESCALATION_DRILL_REPORT.md"
cp "${ROOT_DIR}/drills/templates/ROLLBACK_DRILL_REPORT_TEMPLATE.md" \
  "${OUT_DIR}/ROLLBACK_DRILL_REPORT.md"
cp "${ROOT_DIR}/drills/templates/BACKUP_RESTORE_DRILL_REPORT_TEMPLATE.md" \
  "${OUT_DIR}/BACKUP_RESTORE_DRILL_REPORT.md"

cat > "${OUT_DIR}/README.md" <<README
# Drill Evidence Bundle (${STAMP} UTC)

This folder was generated by:

\`\`\`bash
bash scripts/create_drill_bundle.sh
\`\`\`

## Files
- \`SEV_ESCALATION_DRILL_REPORT.md\`
- \`ROLLBACK_DRILL_REPORT.md\`
- \`BACKUP_RESTORE_DRILL_REPORT.md\`

## Recommended execution order
1. SEV escalation drill
2. Rollback drill
3. Backup/restore drill

## Attachments to add here
- command outputs/log snippets
- screenshots for alert + acknowledgement
- smoke/e2e summaries
README

echo "Created drill bundle: ${OUT_DIR}"
